# TODO 

name: Drug-Classifier Web App CD Pipeline

on:
  # start once the CI pipeline is complete
  workflow_run:
    workflows: ["Drug-Classifier Web App CI Pipeline"]
    types:
      - completed

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deployment To Hugging Face

        # Update the following values regarding your environment
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_REPO_ID: regisklaconsulting/Drug-Classifier-Web-App
          TARGET_BRANCH: to-be-deployed
          LOCAL_PATHS: requirements.txt ./app
        run: make deploy TARGET_BRANCH=$TARGET_BRANCH HF_TOKEN=$HF_TOKEN HF_REPO_ID=$HF_REPO_ID LOCAL_PATHS=$LOCAL_PATHS 



